[package]
name = "bf"
version = "0.1.0"
authors = ["Nelson Earle <nelson.earle137@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
crossterm = "0.17"
itertools = "0.9"
pancurses = { version = "0.16", features = ["wide"] }
structopt = "0.3"
term_size = "0.3"
tui = { version = "0.15.0", features = ["crossterm"] }
