[workspace]
resolver = "2"
members = ["bf*"]

[workspace.dependencies]
# ansi_term = "0.12"
anyhow = "1.0"
crossterm = "0.26"
delegate = "0.10.0"
itertools = "0.11"
ratatui = "0.23"
ratatui-textarea = "0.3"
sha-1 = { version = "0.10", features = ["asm"] }
tracing = "0.1"
