[package]
name = "bf"
version = "0.1.0"
authors = ["Nelson Earle <nelson.earle137@gmail.com>"]
edition = "2021"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
crossterm = "0.24"
itertools = "0.9"
sha-1 = "0.9"
structopt = "0.3"
term_size = "0.3"
textwrap = "0.14"
tui = { version = "0.15", features = ["crossterm"] }
