[package]
name = "bf"
version = "0.1.0"
authors = ["Nelson Earle <nelson.earle137@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
crossterm = "0.17"
itertools = "0.9"
num-integer = "0.1"
structopt = "0.3"
term_size = "0.3"
